### ISSUE TITLE
writing output to file fails if corresponding dir path does not exist

### ISSUE THREAD

**Issue by and2345** [pybind/pybind11_mkdoc#13]
If the output file name contains a non-existing path, trying to open it for writing fails, i.e.

    $ python -m pybind11_mkdoc -o <non/existing/path/out_file.hpp> input_headers...

results in a `FileNotFoundError`.

This can be fixed by adding a call to `os.makedirs(os.path.dirname(output), exist_ok=True)` (requires Python 3.2+).

**Comment by henryiii** [comment]
I don't remember the current state, but I think requiring 3.6+ to run is fine. Or even higher, as it's a developer targeted tool.
